# array
# http.iris.IgnoreServerErrors :
#             - xx
#             - xx
# http.iris.IgnoreServerErrors[1]=""
# http.iris.DisableStartupLog=""
# http.iris.DisableInterruptHandler=""
# http.iris.DisablePathCorrection=""
# http.iris.DisablePathCorrectionRedirection=""
# http.iris.EnablePathEscape=""
# http.iris.EnableOptimizations=""
# http.iris.FireMethodNotAllowed=""
# http.iris.DisableBodyConsumptionOnUnmarshal=""
# http.iris.DisableAutoFireStatusCode=""
# http.iris.Charset="UTF8"
# http.iris.PostMaxMemory=""
# http.iris.TranslateFunctionContextKey=""
# http.iris.TranslateLanguageContextKey=""
# http.iris.ViewLayoutContextKey=""
# http.iris.ViewDataContextKey=""
# http.iris.RemoteAddrHeaders=""
# http.iris.Other=""

http.port: $(http_port|8081)

http.iris.TimeFormat: Jan, Mon 02 2006 15:04:05 GMT